version: '3.8'

services:
  # FastAPI Steganography Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steganography-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - MAX_FILE_SIZE=50
      - REQUEST_TIMEOUT=300
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./app:/app/app:ro  # Mount source code (read-only for security)
      - ./logs:/app/logs   # Mount logs directory
      - uploads:/app/uploads  # Named volume for file uploads
    networks:
      - steganography-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session management (optional)
  redis:
    image: redis:7-alpine
    container_name: steganography-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - steganography-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}

  # Nginx reverse proxy for production (optional)
  nginx:
    image: nginx:alpine
    container_name: steganography-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - api
    networks:
      - steganography-network
    restart: unless-stopped
    profiles:
      - production

# Named volumes
volumes:
  redis_data:
    driver: local
  uploads:
    driver: local

# Networks
networks:
  steganography-network:
    driver: bridge
    name: steganography-network